import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FoldableLinks from "@/components/FoldableLinks";
import CoreConcept from "@/components/CoreConcept";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col`}>
        <div className="flex-1">{children}</div>
        <div>
          <CoreConcept />
        </div>
        <FoldableLinks />
      </body>
    </html>
  );
}
